apiVersion: v1
kind: Pod
metadata:
  labels:
    run: meupodinho
  name: meupodinho
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
      - mountPath: /licao-de-casa
        name: meu-emptydir-de-licao-de-casa

      - mountPath: /dados
        name: temosdados
    args: 
      - sleep
      - "1800"
    resources:
      limits:
        cpu: "0.8"
        memory: "200Mi"

      requests:
        cpu: "0.4"
        memory: "128Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: meu-emptydir-de-licao-de-casa
      emptyDir:
        sizeLimit: 128Mi
    - name: temosdados
      emptyDir:
        sizeLimit: 256Mi
